server:
  port: 9999
spring:
  cache:
    type: redis
    redis:
      time-to-live: 30
      cache-null-values: false
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres