# version: "3.8"
services:
  redis:
    image: redis:7.2.4
    container_name: redis-server
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./data:/data
    ports:
      - "6379:6379"
    restart: always
    command: redis-server /etc/redis/redis.conf --appendonly yes
