version: "3.8"
services:
  redis:
    image: redis:7.2.4
    container_name: redis-server
    volumes:
      - ./cmw/redis/redis.conf:/etc/redis/redis.conf
      - ./cmw/redis/data:/data
    ports:
      - "6379:6379"
    restart: always
    
