spec:
  containers:
    - name: spring-boot-app
      image: your-spring-boot-image
      env:
        # 通过环境变量 JAVA_OPTS 传递 JVM 参数给 Spring Boot 应用程序。
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx512m"
